export default function Terms() {
    return (
        <div className="min-h-screen bg-gray-50">
            {/* Header */}
            <nav className="bg-white border-b px-6 py-4">
                <div className="max-w-4xl mx-auto flex justify-between items-center">
                    <a href="/" className="font-bold text-lg">Studio Genie ✦</a>
                    <a href="/" className="text-gray-600 hover:text-gray-900">← Back to Home</a>
                </div>
            </nav>

            {/* Terms of Use Content */}
            <div className="max-w-4xl mx-auto px-6 py-12">
                <h1 className="text-4xl font-bold mb-4">Terms of Use</h1>
                <p className="text-gray-600 mb-8">Effective Date: December 22, 2025</p>

                <div className="prose prose-lg max-w-none">
                    <h2 className="text-2xl font-bold mt-8 mb-4">1. Introduction</h2>
                    <p className="mb-6">
                        These Terms of Use ("Terms") govern your access to and use of the Studio Genie platform, operated by Make Media Limited ("Studio Genie", "we", "us", or "our").
                    </p>
                    <p className="mb-6">
                        By accessing or using the Services, you agree to be bound by these Terms. If you do not agree, do not use the Services.
                    </p>

                    <h2 className="text-2xl font-bold mt-8 mb-4">2. The Service</h2>
                    <p className="mb-4">
                        Studio Genie provides an AI-powered software platform that enables users to generate videos, scripts, visuals, and related creative content using automated systems and third-party AI technologies.
                    </p>
                    <p className="mb-6">
                        The Services operate automatically. Outputs are generated without human review unless explicitly stated.
                    </p>

                    <h2 className="text-2xl font-bold mt-8 mb-4">3. Accounts</h2>
                    <p className="mb-4">You must create an account to use the Services.</p>
                    <p className="mb-4">You are responsible for:</p>
                    <ul className="list-disc pl-6 mb-6 space-y-2">
                        <li>maintaining the confidentiality of your login credentials</li>
                        <li>all activity under your account</li>
                        <li>ensuring information you provide is accurate and current</li>
                    </ul>
                    <p className="mb-6">Accounts may not be shared, sold, or transferred.</p>

                    <h2 className="text-2xl font-bold mt-8 mb-4">4. AI-Generated Content</h2>
                    <p className="mb-4">
                        All content generated by Studio Genie ("Output") is produced using artificial intelligence and automated systems.
                    </p>
                    <p className="mb-4">You acknowledge and agree that:</p>
                    <ul className="list-disc pl-6 mb-6 space-y-2">
                        <li>Outputs may contain errors, inaccuracies, or unintended results</li>
                        <li>Outputs may not be unique</li>
                        <li>Outputs may resemble content generated for other users</li>
                        <li>Outputs are not guaranteed to comply with platform rules, laws, or regulations</li>
                    </ul>
                    <p className="mb-4">
                        Studio Genie does not provide legal, advertising, compliance, or professional advice.
                    </p>
                    <p className="mb-6">
                        You are solely responsible for reviewing, validating, and approving any Output before use.
                    </p>

                    <h2 className="text-2xl font-bold mt-8 mb-4">5. Ownership & Usage Rights</h2>
                    <p className="mb-4">You retain ownership of the content you input into the platform.</p>
                    <p className="mb-4">Subject to compliance with these Terms:</p>
                    <ul className="list-disc pl-6 mb-6 space-y-2">
                        <li>You own the Outputs generated while your account is active</li>
                        <li>You may use Outputs commercially without attribution</li>
                    </ul>
                    <p className="mb-4">Studio Genie retains all rights to:</p>
                    <ul className="list-disc pl-6 mb-6 space-y-2">
                        <li>software</li>
                        <li>models</li>
                        <li>infrastructure</li>
                        <li>interfaces</li>
                        <li>algorithms</li>
                        <li>platform design</li>
                    </ul>
                    <p className="mb-6">No rights are granted except as expressly stated.</p>

                    <h2 className="text-2xl font-bold mt-8 mb-4">6. Credits, Billing & Payments</h2>
                    <p className="mb-4">Studio Genie operates on a credit-based system.</p>
                    <ul className="list-disc pl-6 mb-6 space-y-2">
                        <li>Credits are consumed when generating videos or content</li>
                        <li>Credit usage is final once processing begins</li>
                        <li>Credits do not roll over unless explicitly stated</li>
                    </ul>

                    <h3 className="text-xl font-semibold mt-6 mb-3">No Refund Policy</h3>
                    <p className="mb-4">
                        <strong>All purchases, including subscriptions and credit packs, are non-refundable</strong>, except where required by law.
                    </p>
                    <p className="mb-4">
                        Unused credits have no cash value and cannot be exchanged or refunded.
                    </p>
                    <p className="mb-6">Chargebacks or payment disputes may result in:</p>
                    <ul className="list-disc pl-6 mb-6 space-y-2">
                        <li>account suspension</li>
                        <li>loss of credits</li>
                        <li>permanent termination</li>
                    </ul>

                    <h2 className="text-2xl font-bold mt-8 mb-4">7. Acceptable Use</h2>
                    <p className="mb-4">You agree not to use the Services to:</p>
                    <ul className="list-disc pl-6 mb-6 space-y-2">
                        <li>violate laws or regulations</li>
                        <li>generate unlawful, harmful, or deceptive content</li>
                        <li>infringe intellectual property or privacy rights</li>
                        <li>misrepresent AI-generated content where disclosure is legally required</li>
                        <li>attempt to reverse engineer or abuse the platform</li>
                    </ul>
                    <p className="mb-6">We reserve the right to suspend or terminate accounts at our discretion.</p>

                    <h2 className="text-2xl font-bold mt-8 mb-4">8. Availability & Performance</h2>
                    <p className="mb-4">The Services are provided "as is" and "as available."</p>
                    <p className="mb-4">We do not guarantee:</p>
                    <ul className="list-disc pl-6 mb-6 space-y-2">
                        <li>uninterrupted service</li>
                        <li>error-free operation</li>
                        <li>specific results or performance</li>
                    </ul>
                    <p className="mb-6">
                        Downtime, delays, or failures may occur due to maintenance, infrastructure issues, or third-party services.
                    </p>

                    <h2 className="text-2xl font-bold mt-8 mb-4">9. Limitation of Liability</h2>
                    <p className="mb-4">To the maximum extent permitted by law:</p>
                    <ul className="list-disc pl-6 mb-6 space-y-2">
                        <li>Studio Genie is not liable for indirect, incidental, or consequential damages</li>
                        <li>Our total liability will not exceed the greater of £100 or the amount paid by you in the last 12 months</li>
                        <li>You use the Services at your own risk.</li>
                    </ul>

                    <h2 className="text-2xl font-bold mt-8 mb-4">10. Indemnification</h2>
                    <p className="mb-4">You agree to indemnify and hold harmless Make Media Limited from any claims arising from:</p>
                    <ul className="list-disc pl-6 mb-6 space-y-2">
                        <li>your use of Outputs</li>
                        <li>your content or Inputs</li>
                        <li>your violation of laws or third-party rights</li>
                        <li>your commercial use of generated content</li>
                    </ul>

                    <h2 className="text-2xl font-bold mt-8 mb-4">11. Termination</h2>
                    <p className="mb-4">You may stop using the Services at any time.</p>
                    <p className="mb-4">We may suspend or terminate access if:</p>
                    <ul className="list-disc pl-6 mb-6 space-y-2">
                        <li>these Terms are violated</li>
                        <li>misuse or abuse is detected</li>
                        <li>required by law</li>
                    </ul>
                    <p className="mb-6">Termination does not entitle you to refunds.</p>

                    <h2 className="text-2xl font-bold mt-8 mb-4">12. Governing Law</h2>
                    <p className="mb-6">
                        These Terms are governed by the laws of England and Wales.
                    </p>
                    <p className="mb-6">
                        Any disputes shall be resolved exclusively in that jurisdiction.
                    </p>

                    <h2 className="text-2xl font-bold mt-8 mb-4">13. Changes to These Terms</h2>
                    <p className="mb-8">
                        We may update these Terms from time to time. Continued use of the Services after changes means you accept the updated Terms.
                    </p>

                    <div className="mt-12 pt-8 border-t">
                        <p className="text-gray-600">
                            For questions about these Terms, please contact us at <a href="mailto:help@studiogenie.ai" className="text-violet-600 hover:underline">help@studiogenie.ai</a>.
                        </p>
                    </div>
                </div>
            </div>

            {/* Footer */}
            <footer className="bg-gray-900 text-white py-8 mt-12">
                <div className="max-w-4xl mx-auto px-6 text-center">
                    <p className="text-gray-400">© 2025 Studio Genie. All rights reserved.</p>
                </div>
            </footer>
        </div>
    );
}
